base_model: Qwen/Qwen-7B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /home/LeiFeng/lzy/lora-merge/qwen/fft/filter-load_bigbench-load_truthfulqa-threshold_3.0_16.128677009210804_7987.json
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./out

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 2
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_ratio: 0.05
evals_per_epoch: 0
eval_table_size:
saves_per_epoch: 1
save_total_limit: 1
debug:
deepspeed: /home/LeiFeng/lzy/axolotl/src/deepspeed/zero3.json
weight_decay: 0.0
fsdp:
fsdp_config:
