base_model: /data/models/Llama-2-7b-hf
base_model_config: /data/models/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: garage-bAInd/Open-Platypus
    type: alpaca
dataset_prepared_path:
val_set_size: 0
output_dir: /data/outs/lora2LORA/7b-llora-out-k

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter: llora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: false
lora_fan_in_fan_out:
lora_target_modules:
  - k_proj


small_r: 32
large_r: 32
small_model_dim: 4096
large_model_dim: 5120
small_model_intermediate_size: 11008
large_model_intermediate_size: 13824

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_hf
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps:
eval_steps:
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
