base_model: meta-llama/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /data/data/final_set_cleaned/train/
    type: sharegpt
    conversation: chatml
  - path: /data/data/map_coig_cqia.jsonl
    type: sharegpt
    conversation: chatml
  - path: /data/data/ruozhiba.jsonl
    type: sharegpt
    conversation: chatml
dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./out

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

wandb_project: FFT
wandb_entity:
wandb_watch:
wandb_name: llama3-fft
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 4
num_epochs: 2
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 0
eval_table_size:
saves_per_epoch: 4
save_total_limit: 8
debug:
deepspeed: /home/LeiFeng/lzy/axolotl/src/deepspeed/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
default_system_message: "You are a helpful assistant."
special_tokens:
  eos_token: "<|im_end|>"
  pad_token: "<|end_of_text|>"
tokens:
  - "<|im_start|>"
  - "<|im_end|>"
